eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: service-zuul
zuul:
  ignoredServices: '*'
  routes:
    api-a:
      path: /api-a/**
      url: http://localhost:8080/send/topic3
    api-b:
      path: /api-b/**
      serviceId: service-feign